# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='intro',
            field=models.TextField(default='', verbose_name='\u680f\u76ee\u7b80\u4ecb'),
        ),
    ]
